version: 2
jobs:
  build:
    # Set Docker image
    docker:
      - image: equanz/key-notify-server
    working_directory: /go/src/github.com/equanz/key-notify-server

    steps:
      - checkout

      # Install requirements
      - run:
          name: Install dep and requirements
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
            npm install
            npm run eslint

      # Run static code analyzer
      - run:
          name: Run static code analyzer(go vet)
          command: go vet $(go list ./... | grep -v /vendor/)

      # Run eslint
      - run:
          name: Run ESLint (in app/assets/)
          command: npm run eslint

